---
title: "Analyzing Storm Data"
output:
  pdf_document: default
  html_document: default
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

#Librarys used for analysis
```{r}
library(R.utils)
library(memoise)
```
#Downloading file
I copied the url from the cource website
```{r}
flocation <- "https://d396qusza40orc.cloudfront.net/repdata%2Fdata%2FStormData.csv.bz2"
filename <- "stormdata.bz2"
if(!file.exists("stormdata.bz2")){
download.file(flocation,filename,mode="wb")
    paste("File was downloaded on",Sys.time())
}
```
#Extracting file
```{r}
if(!file.exists("stormdata.csv")){
bunzip2("stormdata.bz2","stormdata.csv",remove=FALSE)
}
```
#Reading file
```{r,cache=TRUE}
  sdata <- read.csv("stormdata.csv")
  data = subset(sdata, select=c(EVTYPE,FATALITIES,INJURIES,PROPDMG,PROPDMGEXP,CROPDMG,CROPDMGEXP))
```
#Property damage multiplier in column "PROPDMGEXP"
```{r,cache=TRUE}
data$PROPEXP[data$PROPDMGEXP == "K"] <- 1000
data$PROPEXP[data$PROPDMGEXP == "M"] <- 1e+06
data$PROPEXP[data$PROPDMGEXP == ""] <- 1
data$PROPEXP[data$PROPDMGEXP == "B"] <- 1e+09
data$PROPEXP[data$PROPDMGEXP == "m"] <- 1e+06
data$PROPEXP[data$PROPDMGEXP == "0"] <- 1
data$PROPEXP[data$PROPDMGEXP == "5"] <- 1e+05
data$PROPEXP[data$PROPDMGEXP == "6"] <- 1e+06
data$PROPEXP[data$PROPDMGEXP == "4"] <- 10000
data$PROPEXP[data$PROPDMGEXP == "2"] <- 100
data$PROPEXP[data$PROPDMGEXP == "3"] <- 1000
data$PROPEXP[data$PROPDMGEXP == "h"] <- 100
data$PROPEXP[data$PROPDMGEXP == "7"] <- 1e+07
data$PROPEXP[data$PROPDMGEXP == "H"] <- 100
data$PROPEXP[data$PROPDMGEXP == "1"] <- 10
data$PROPEXP[data$PROPDMGEXP == "8"] <- 1e+08
# give 0 to invalid exponent data, so they not count in
data$PROPEXP[data$PROPDMGEXP == "+"] <- 0
data$PROPEXP[data$PROPDMGEXP == "-"] <- 0
data$PROPEXP[data$PROPDMGEXP == "?"] <- 0
# compute the property damage value
data$PROPDMGVAL <- data$PROPDMG * data$PROPEXP
```
#Crop damage multiplier in column "CROPDMGEXP"
```{r,cache=TRUE}
# Sorting the property exponent data
data$CROPEXP[data$CROPDMGEXP == "M"] <- 1e+06
data$CROPEXP[data$CROPDMGEXP == "K"] <- 1000
data$CROPEXP[data$CROPDMGEXP == "m"] <- 1e+06
data$CROPEXP[data$CROPDMGEXP == "B"] <- 1e+09
data$CROPEXP[data$CROPDMGEXP == "0"] <- 1
data$CROPEXP[data$CROPDMGEXP == "k"] <- 1000
data$CROPEXP[data$CROPDMGEXP == "2"] <- 100
data$CROPEXP[data$CROPDMGEXP == ""] <- 1
# give 0 to invalid exponent data, so they not count in
data$CROPEXP[data$CROPDMGEXP == "?"] <- 0
# compute the crop damage value
data$CROPDMGVAL <- data$CROPDMG * data$CROPEXP
```
```{r,cache=TRUE}
# Total of all property damage by events
fat <- aggregate(FATALITIES ~ EVTYPE, data = data, FUN = sum)
inj <- aggregate(INJURIES ~ EVTYPE, data = data, FUN = sum)
pdmg <- aggregate(PROPDMGVAL ~ EVTYPE, data = data, FUN = sum)
cdmg <- aggregate(CROPDMGVAL ~ EVTYPE, data = data, FUN = sum)
```
#RESULTS

# Damage to HUMAN due to natural events
```{r}
orderf <- fat[order(-fat$FATALITIES), ][1:5, ]
orderi <- inj[order(-inj$INJURIES), ][1:5, ]
par(mfrow = c(1, 2))
barplot(orderf$FATALITIES, las = 3, names.arg = orderf$EVTYPE, main = "Top 5 Highest Fatalities", ylab = "number of fatalities", col = "blue")

barplot(orderi$INJURIES, las = 3, names.arg = orderi$EVTYPE, main = "Top 5 Highest Injuries", ylab = "number of injuries", col = "blue")

```
#Damage to property due to natual events
```{r}
propdmg <- pdmg[order(-pdmg$PROPDMGVAL), ][1:5, ]
cropdmg <- cdmg[order(-cdmg$CROPDMGVAL), ][1:5, ]
par(mfrow = c(1, 2))
barplot(propdmg$PROPDMGVAL/(10^9), las = 3, names.arg = propdmg$EVTYPE, 
    main = "Top 5 Greatest Property Damages", ylab = "Cost of damage ($ billions)", 
    col = "red")
barplot(cropdmg$CROPDMGVAL/(10^9), las = 3, names.arg = cropdmg$EVTYPE, 
    main = "Top 5 Greatest Crop Damages", ylab = "Cost of damage ($ billions)", 
    col = "red")
```